### ISSUE TITLE
Automatically choose size and compensation

### ISSUE THREAD

**Issue by edwilliams** [FujiHaruka/node-adaptive-threshold#2]
Hi @FujiHaruka, I’m building an app that scans documents in a similar way to Scanbot - Scanbot always seems to choose the right settings for a document (when processing it black and white I.e. Thea holding). Are you aware of any way to determine the ideal size and compensation settings to process a black and white document (say, a letter as per your example, with very small print)?

**Comment by FujiHaruka** [comment]
Hi @edwilliams .
I think, in many cases one setting ( for example, size = 5, compensation = 7) goes well because adaptive threshold algorithm is designed for the purpose.

But if it doesn't goes well in some case, you might find better threshold algorithm. but I don't have enough knowledge about what is better algorithm .... 😓

**Comment by edwilliams** [comment]
Thanks @FujiHaruka, I've done a [bit of reading](http://homepages.inf.ed.ac.uk/rbf/HIPR2/adpthrsh.htm) on adaptive thresholding (...I wasn't aware of the difference between adaptive and global!) Was previously using [this repo](https://github.com/canastro/image-filter-threshold) - yours is far better!
